apiVersion: apps/v1
kind: Deployment

metadata:
  name: api
  namespace: moderation

spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: node
        image: registry.digitalocean.com/free-draw/moderation-api
        env:
        - name: PORT
          value: "80"
          # Secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: secret
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: discord-oauth2
              key: client-id
        - name: DISCORD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: discord-oauth2
              key: client-secret
          # External services
        - name: REDIS_HOST
          value: "redis-master.moderation"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        - name: MONGODB_HOST
          value: "mongodb.moderation"
        - name: MONGODB_DATABASE
          value: "moderation"
        - name: MONGODB_USER
          value: "root"
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-root-password
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service

metadata:
  name: api
  namespace: moderation

spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
