apiVersion: apps/v1
kind: Deployment

metadata:
  name: socket
  namespace: moderation

spec:
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
    spec:
      restartPolicy: Always
      containers:
      - name: node
        image: registry.digitalocean.com/free-draw/moderation-socket
        env:
        - name: PORT
          value: "80"
          # External services
        - name: REDIS_HOST
          value: "redis-master.moderation"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service

metadata:
  name: socket
  namespace: moderation

spec:
  selector:
    app: socket
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 900