apiVersion: apps/v1
kind: Deployment

metadata:
  name: website
  namespace: moderation
  labels:
    app: website

spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: registry.digitalocean.com/free-draw/moderation-website
        resources:
          limits:
            memory: "64Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service

metadata:
  name: website
  namespace: moderation

spec:
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
