apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ .Release.Name }}-discord-application
  namespace: {{ .Release.Namespace }}

data:
  client-id: {{ .Values.discord.clientId | b64enc }}
  client-secret: {{ .Values.discord.clientSecret | b64enc }}
  token: {{ .Values.discord.token | b64enc }}
  redirect-url: {{ .Values.discord.redirectUrl | b64enc }}