apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ .Release.Name }}-discord
  namespace: {{ .Release.Namespace }}

data:
  id: {{ .Values.discord.id | toString | b64enc }}
  secret: {{ .Values.discord.secret | b64enc }}