apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ .Release.Name }}-discord
  namespace: {{ .Release.Namespace }}

data:
  oauth2-client-id: {{ .Values.discord.oauth2.id | toString | b64enc }}
  oauth2-client-secret: {{ .Values.discord.oauth2.secret | b64enc }}