apiVersion: v1
kind: Secret
type: Opaque

{{ $name := printf "%s-discord" .Release.Name }}
{{ $existingSecret := lookup "v1" "Secret" .Release.Namespace $name }}

metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}

data:
  {{ if .Values.discord.oauth2.id }}
  oauth2-client-id: {{ .Values.discord.oauth2.id | toString | b64enc }}
  {{ else if $existingSecret }}
  oauth2-client-id: {{ index $existingSecret.data "oauth2-client-id" }}
  {{ end }}
  {{ if .Values.discord.oauth2.secret }}
  oauth2-client-secret: {{ .Values.discord.oauth2.secret | b64enc }}
  {{ else if $existingSecret }}
  oauth2-client-secret: {{ index $existingSecret.data "oauth2-client-secret" }}
  {{ end }}