apiVersion: v1
kind: Secret
type: Opaque

{{ $name := printf "%s-jwt" .Release.Name }}
{{ $existingSecret := lookup "v1" "Secret" .Release.Namespace $name }}

metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}

data:
  {{ if .Values.jwt }}
  secret: {{ .Values.jwt }}
  {{ else if $existingSecret }}
  secret: {{ index $existingSecret.data "secret" }}
  {{ else }}
  secret: {{ randAlphaNum 256 | b64enc }}
  {{ end }}