apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ .Release.Name }}-services
  namespace: {{ .Release.Namespace }}

data:
  redis-url: {{ .Values.redis.url | b64enc }}
  {{ if .Values.redis.cert }}
  redis-cert: {{ .Values.redis.cert | b64enc }}
  {{ end }}
  mongodb-url: {{ .Values.mongodb.url | b64enc }}
  {{ if .Values.mongodb.cert }}
  mongodb-cert: {{ .Values.mongodb.cert | b64enc }}
  {{ end }}