apiVersion: v1
kind: Secret
type: Opaque

{{ $name := printf "%s-services" .Release.Name }}
{{ $existingSecret := lookup "v1" "Secret" .Release.Namespace $name }}

metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}

data:
  {{ if .Values.redis }}
  redis: {{ .Values.redis | b64enc }}
  {{ else if $existingSecret }}
  redis: {{ index $existingSecret.data "redis" }}
  {{ end }}
  {{ if .Values.mongodb }}
  mongodb: {{ .Values.mongodb | b64enc }}
  {{ else if $existingSecret }}
  mongodb: {{ index $existingSecret.data "mongodb" }}
  {{ end }}