apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    matchLabels:
      app: api
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: api
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      volumes:
      - name: certs
        secret:
          secretName: {{ .Release.Name }}-services
          items:
          {{ if .Values.mongodb.cert }}
          - key: mongodb-cert
            path: mongodb.crt
          {{ end }}
          {{ if .Values.redis.cert }}
          - key: redis-cert
            path: redis.crt
          {{ end }}
      containers:
      - name: node
        image: ghcr.io/free-draw/moderation-api:main
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "80"
          # Secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-jwt
              key: secret
        - name: DISCORD_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-discord
              key: id
        - name: DISCORD_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-discord
              key: secret
        - name: REDIS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-services
              key: redis-url
        - name: MONGODB
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-services
              key: mongodb-url
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: certs
          mountPath: "/etc/certs"
          readOnly: true
---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: api
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
