apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    matchLabels:
      app: api
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: api
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
      - name: node
        image: ghcr.io/free-draw/moderation-api:main
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "80"
          # Secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-jwt
              key: secret
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-discord
              key: oauth2-client-id
        - name: DISCORD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-discord
              key: oauth2-client-secret
          # External services
        - name: REDIS_HOST
          value: "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-services
              key: redis-password
        - name: MONGODB_HOST
          value: "{{ .Release.Name }}-mongodb.{{ .Release.Namespace }}"
        - name: MONGODB_DATABASE
          value: "{{ .Release.Namespace }}"
        - name: MONGODB_USER
          value: moderation
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-services
              key: mongodb-password
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: api
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
