apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-website
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    matchLabels:
      app: website
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: website
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      imagePullPolicy: always
      containers:
      - name: nginx
        image: ghcr.io/free-draw/moderation-website:main
        resources:
          limits:
            memory: "64Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service

metadata:
  name: website
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: website
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
