apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ .Release.Name }}-jwt
  namespace: {{ .Release.Namespace }}

data:
  {{ if .Values.jwt -}}
  secret: {{ .Values.jwt | b64enc }}
  {{- else -}}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-jwt" .Release.Name) -}}
  {{- if $existingSecret -}}
  secret: {{ $existingSecret.data.secret }}
  {{- else -}}
  secret: {{ randAlphaNum 128 | b64enc }}
  {{- end -}}
  {{- end }}