apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    matchLabels:
      app: api
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: api
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      volumes:
        {{- include "volumes.certs.mongodb" . | nindent 6 }}
      containers:
      - name: node
        image: ghcr.io/free-draw/moderation-api:main
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
        env:
        - name: ADDRESS
          value: "0.0.0.0"
        - name: PORT
          value: "80"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-jwt
              key: secret
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-discord
              key: client-id
        - name: DISCORD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-discord
              key: client-secret
        - name: DISCORD_REDIRECT_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-discord
              key: redirect-url
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-urls
              key: mongodb
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-urls
              key: redis
        volumeMounts:
          {{- include "volumeMounts.certs.mongodb" . | nindent 8 }}
---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: api
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80