apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-discord
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    matchLabels:
      app: discord
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: discord
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-configs
            items:
            - key: discord.json
              path: discord.json
      containers:
      - name: node
        image: ghcr.io/free-draw/moderation-discord:main
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /app/config.json
          subPath: discord.json
        resources:
          limits:
            memory: "256Mi"
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-jwt
              key: secret
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-discord-application
              key: client-id
        - name: DISCORD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-discord-application
              key: client-secret
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-discord-application
              key: token
        - name: API_URL
          value: "{{ .Release.Name }}-api.{{ .Release.Namespace }}"
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-tokens
              key: discord
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-urls
              key: redis