apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-realtime
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    matchLabels:
      app: realtime
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: realtime
        release: {{ .Release.Name }}
      annotations:
        linkerd.io/inject: enabled
    spec:
      restartPolicy: Always
      containers:
      - name: node
        image: ghcr.io/free-draw/moderation-realtime:main
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-urls
              key: redis
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-jwt
              key: secret
---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-realtime
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: realtime
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 900